# Generated by Django 3.2.23 on 2024-01-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0003_auto_20240129_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictFlowDB',
        ),
        migrations.AddField(
            model_name='optimaldb',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
