# Generated by Django 3.2.23 on 2024-01-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0004_auto_20240130_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimaldb',
            old_name='point',
            new_name='Predict_Route_Traffic_Flow',
        ),
    ]
