# Generated by Django 3.2.23 on 2024-01-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0005_rename_point_optimaldb_predict_route_traffic_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimaldb',
            name='Destination',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimaldb',
            name='Source',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
