# Generated by Django 3.2.23 on 2024-01-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0006_auto_20240130_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optimaldb',
            name='Predict_Route_Traffic_Flow',
        ),
    ]
