# Generated by Django 3.2.23 on 2024-01-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0007_remove_optimaldb_predict_route_traffic_flow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_Model', models.CharField(choices=[('Select', 'Select'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('saes', 'SAES'), ('new_saes', 'NEW_SAES'), ('rnn', 'RNN'), ('average', 'AVERAGE')], default='Select', max_length=20)),
                ('Predict_Route_Traffic_Flow', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='optimaldb',
            name='Destination',
            field=models.IntegerField(default=4013),
        ),
        migrations.AlterField(
            model_name='optimaldb',
            name='Source',
            field=models.IntegerField(default=2911),
        ),
    ]
