# Generated by Django 3.2.23 on 2024-01-31 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0008_auto_20240130_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowdb',
            old_name='Select_Model',
            new_name='Model',
        ),
    ]
