# Generated by Django 3.2.23 on 2024-01-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0009_rename_select_model_flowdb_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlowDB',
        ),
    ]
