# Generated by Django 3.2.23 on 2024-01-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0011_optimaltest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptimalTest',
        ),
    ]
