# Generated by Django 3.2.23 on 2024-01-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0012_delete_optimaltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('Select', 'Select'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('saes', 'SAES'), ('new_saes', 'NEW_SAES'), ('rnn', 'RNN'), ('average', 'AVERAGE')], default='Select', max_length=20)),
                ('point', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
