# Generated by Django 3.2.23 on 2024-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0013_flowdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowdb',
            old_name='model',
            new_name='Predict_Route_Traffic',
        ),
        migrations.RenameField(
            model_name='flowdb',
            old_name='point',
            new_name='Route',
        ),
        migrations.AlterField(
            model_name='optimaldb',
            name='Destination',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='optimaldb',
            name='Source',
            field=models.IntegerField(),
        ),
    ]
