# Generated by Django 3.2.23 on 2024-02-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0014_auto_20240131_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowdb',
            name='Predict_Route_Traffic',
            field=models.CharField(choices=[('Select', 'SELECT'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('saes', 'SAES'), ('new_saes', 'NEW_SAES'), ('rnn', 'RNN'), ('average', 'AVERAGE')], default='Select', max_length=20),
        ),
        migrations.AlterField(
            model_name='optimaldb',
            name='Select_Model',
            field=models.CharField(choices=[('Select', 'SELECT'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('saes', 'SAES'), ('new_saes', 'NEW_SAES'), ('rnn', 'RNN'), ('average', 'AVERAGE')], default='Select', max_length=20),
        ),
    ]
