# Generated by Django 4.1.5 on 2024-02-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0015_auto_20240210_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowdb',
            old_name='Predict_Route_Traffic',
            new_name='Forecast_Route_Traffic',
        ),
    ]
