# Generated by Django 4.1.5 on 2024-02-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onepage', '0017_rename_forecast_route_traffic_flowdb_predict_route_traffic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowdb',
            old_name='Predict_Route_Traffic',
            new_name='Forecast_Route_Traffic',
        ),
    ]
